prefix=${CMAKE_INSTALL_PREFIX}
exec_prefix=${CMAKE_INSTALL_FULL_BINDIR}
libdir=${CMAKE_INSTALL_FULL_LIBDIR}
includedir=${CMAKE_INSTALL_FULL_INCLUDEDIR}/${JREEN_INCLUDE_PATH}/

Name: libjreen${JREEN_SUFFIX}
Description: Qt Jabber/XMPP extensible library
Requires: Qt${JREEN_QT_MIDDLE}Core Qt${JREEN_QT_MIDDLE}Network
Version: ${CMAKE_JREEN_VERSION_MAJOR}.${CMAKE_JREEN_VERSION_MINOR}.${CMAKE_JREEN_VERSION_PATCH}
Libs: -L${CMAKE_INSTALL_FULL_LIBDIR} -ljreen${JREEN_SUFFIX}
Cflags: -I${CMAKE_INSTALL_FULL_INCLUDEDIR}/${JREEN_INCLUDE_PATH}/

